adjustVelocity(0.787)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("o", 0.5, bpm)
rest(1, bpm)
keypress("u", 0.5, bpm)
rest(4, bpm)
keypress("Y", 0.5, bpm)
rest(2, bpm)
keypress("T", 0.5, bpm)
rest(2, bpm)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("o", 0.5, bpm)
rest(1, bpm)
keypress("u", 0.5, bpm)
rest(4, bpm)
keypress("Y", 0.5, bpm)
rest(2, bpm)
keypress("T", 0.5, bpm)
rest(2, bpm)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("o", 0.5, bpm)
rest(1, bpm)
keypress("u", 0.5, bpm)
rest(4, bpm)
keypress("Y", 0.5, bpm)
rest(2, bpm)
keypress("T", 0.5, bpm)
rest(16.5, bpm)
keypress("*", 0.5, bpm)
rest(0.5, bpm)
keypress("8", 0.5, bpm)
rest(4.5, bpm)
keypress("^", 0.5, bpm)
rest(0.5, bpm)
keypress("8", 1, bpm)
rest(1, bpm)
keypress("W", 0.25, bpm)
rest(0.5, bpm)
keypress("w", 0.5, bpm)
rest(1, bpm)
keypress("*", 0.5, bpm)
rest(0.5, bpm)
keypress("8", 0.5, bpm)
rest(0.5, bpm)
keypress("*", 0.5, bpm)
rest(0.5, bpm)
keypress("8", 2, bpm)
rest(2, bpm)
keypress("^", 1.5, bpm)
rest(1.5, bpm)
keypress("^", 0.5, bpm)
rest(0.5, bpm)
keypress("8", 1.5, bpm)
rest(4, bpm)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("o", 0.5, bpm)
rest(1, bpm)
keypress("u", 0.5, bpm)
rest(4, bpm)
keypress("Y", 0.5, bpm)
rest(2, bpm)
keypress("T", 0.5, bpm)
rest(2, bpm)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
rest(3.5, bpm)
keypress("E", 0.5, bpm)
rest(0.5, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("T", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)
keypress("t", 0.5, bpm)
rest(1, bpm)
keypress("s", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(1, bpm)
keypress("o", 0.5, bpm)
rest(1, bpm)
keypress("u", 0.5, bpm)
rest(4, bpm)
keypress("Y", 0.5, bpm)
rest(2, bpm)
keypress("T", 0.5, bpm)
rest(1, bpm)
keypress("Y", 1, bpm)
rest(33, bpm)
keypress("D", 0.5, bpm)
rest(4, bpm)
keypress("i", 0.5, bpm)
rest(2, bpm)
keypress("i", 0.5, bpm)
rest(0.5, bpm)
keypress("o", 0.5, bpm)
rest(0.5, bpm)
keypress("O", 0.5, bpm)
rest(0.5, bpm)
keypress("P", 0.5, bpm)
rest(0.5, bpm)
keypress("s", 0.5, bpm)

finishedSong()
